#pragma once

#include <ranges>
#include <vector>

template <typename Event>
struct ConfigCheckResult{
    bool is_config;
    std::vector<Event> trace; // Only populated if is_config is true, or if a maximal trace is reached without finding a configuration (if MultiLinearizations is false)

    constexpr explicit operator bool() const noexcept{
        return is_config; // Valid if is_config is true
    }
};

/**
 * Checks if a given set of events is a configuration of the event structure by using a trace generator to explore all possible linearizations of that set. It implements the definition of a configuration saying a candidate set is a configuration if there exists a linearization of it that is a valid trace of the same event structure.
 * It simply checks if one of the traces generated by the trace generator includes all the events in the candidate set. If it finds such a trace, it returns true along with that trace. If it exhausts all traces without finding one that includes all events in the candidate set, it returns false.
 * For bundle, stable and prime ESs, there is no need to check all traces/permutations once a maximal trace is found. By then, either the maximal trace includes all the events of the candidate set (then the candidate set is a configuration), or it does not (then the candidate set is not a configuration). 
 * However the situation is different for asymmetric conflict such as in extended bundle ESs, where we might reach a maximal trace in one order that does not include some inhibited events of the candidate set, but if we explore the same events in a different order we might reach a different maximal trace that includes those inhibited events before they are inhibited, and thus includes all events of the candidate set. In this case, we need to explore all traces/permutations to be sure that the candidate set is not a configuration.
 * Therefore the function has a template parameter MultiLinearizations that can be set to false to stop the exploration after the first maximal trace is found, which is enough for structures like prime, stable and bundle ESs, but should be set to true for extended bundle ESs to be sure of the result. For safety and correctness it defaults to true, but it can be set to false for better performance when we know that the structure we are dealing with does not have asymmetric conflicts.
 * The function returns a ConfigCheckResult struct that indicates whether the candidate set is a configuration and includes one of the traces that demonstrates it (if it is a configuration) or one of the maximal traces that fails to demonstrate it (if it is not a configuration). This can be useful for debugging and understanding why a particular set of events is or is not a configuration.
 * The trace generator is expected to generate traces that are valid according to the event structure's enabling and conflict logic, and shall generate traces with events from the candidate set only, so the correctness of this function relies on the correctness of the trace generator it uses. The generator can be a BFS but it is preferred to be a DFS, as we are eager to reach the first trace that has the same events of the candidate set, and a DFS is more likely to reach it faster than a BFS.
 */
template <bool MultiLinearizations = true, typename TraceGenFactory>
auto isConfiguration(const auto& candidateSet, TraceGenFactory&& genFactory) {
    
    using Event = std::ranges::range_value_t<decltype(candidateSet)>;

    auto traceEngine = genFactory(candidateSet);
    auto gen = traceEngine();

    while (gen.next()) {
        auto result = gen.move_value();
        // If we found a trace that fired every event in our set, it's a configuration
        if (result.path.size() == std::ranges::size(candidateSet))
            return ConfigCheckResult<Event>{true, std::move(result.path)};
        
        if constexpr (!MultiLinearizations){
            if(result.is_maximal)
                return ConfigCheckResult<Event>{false, std::move(result.path)}; // If we only care about one linearization, stop after the first maximal trace
        }
    }
    // If the generator exhausts all valid paths within the set 
    // and never reaches the target size, it's not a configuration.
    return ConfigCheckResult<Event>{false, {}};
}

